- fnctl/routes.go
> fnctl: heroku-like configuration for routes

- api/runner/async_runner.go
- api/runner/async_runner_test.go
- api/runner/runner.go
- api/runner/worker.go
- api/server/apps_test.go
- api/server/routes_test.go
- api/server/runner.go
- api/server/runner_async_test.go
- api/server/runner_test.go
- api/server/server.go
- api/server/server_test.go
- docs/options.md
- main.go
This is a proposal that addresses concerns some aspects of https://github.com/iron-io/functions/issues/165  and https://github.com/iron-io/functions/issues/69.
1 - We have now a supervised goroutine that spawns workers for the incoming load. They serve any kind of request, sync or async (#165)
2 - Because runners start are separate from request life-cycle, we would be a third way closer to have hot reusable containers (#69)
Edit: 
***Implementation Details***
This PR introduces new goroutine responsible solely for executing tasks. It interfaces with the HTTP server and async modules through a channel, whose contents holds both the task information, and a channel to send the answer backer to the caller. https://github.com/iron-io/functions/blob/bounded-concurrency/api/server/runner.go#L183- …
> functions: common concurrency stream for sync and async

- api/datastore/bolt/bolt.go
- api/datastore/postgres/postgres.go
- api/models/route.go
- api/server/runner.go
- api/server/runner_test.go
- docs/swagger.yml
- fn/funcfile.go
- fn/routes.go
Fix https://github.com/iron-io/functions/issues/339
> functions: fix route timeout

- docs/swagger.yml
- fn/publish.go
- fn/routes.go
Partially addresses #361 
Partially addresses #364
> api: remove app_name duplication of route related calls

- api/datastore/bolt/bolt.go
- api/datastore/bolt_test.go
- api/datastore/datastore_test.go
- api/datastore/postgres/postgres.go
- api/datastore/postgres_test.go
- api/models/datastore.go
The postgres Put method was saving the key as value during updates.
Also added an error if the key is empty.
And added some tests to expect the correct behavior.
> Fix datastore Put and added tests

- fn/routes.go
- fn/run.go
Some enviroments (for example like mine) has some env values that causes some unexpected behaviors in the `fn call`. Users with the same kind of env might have problems running examples.
Only call envAsHeader if the -e flag has at least one selected env variable.
> Disable envAsHeader by default

- api/datastore/bolt/bolt.go
Postgres is overwriting it right now.
Fixes #453 (To delete single keys the client will have to handle it, that's what is happening right now in `fn`)
> Overwrite config/headers on update using boltdb

- THIRD_PARTY
- api/server/apps_test.go
- api/server/internal/routecache/lru.go
- api/server/routes_create.go
- api/server/routes_delete.go
- api/server/routes_test.go
- api/server/routes_update.go
- api/server/runner.go
- api/server/runner_test.go
- api/server/server.go
- api/server/server_test.go
- api/server/special_handler_test.go
Use a global LRU for routes matching during function calls
> Add global lru for routes with keys being the appname + path

- CHANGELOG.md
- api/datastore/bolt/bolt.go
- api/mqs/bolt.go
- api/runner/async_runner.go
- api/server/server.go
- init.go
- Fixed env PORT was not working correctly because viper.AutomaticEnv was positioned in the wrong place.
- API serve not using gin.Engine.Run because using that method we can't know when the server is already listening in the specified port.
- Some log changes
Closes #482
> API initialization changes

- fn/routes.go
- fn/run.go
- fn/run_others.go
- fn/run_windows.go
- fn/testfn.go
Fixes #503 
This change aligns `run` and `call`'s choice of http method in the default case (`POST` if data present, otherwise `GET`), and adds an explicit `method` flag as well.
> improve fn run/call http method support

- fn/README.md
fn's README should say "Bump, Build" rather than "Build, Bump" because it is necessary to bump before you build so that the docker image that is created will have the correct version tag.
> Change build-then-bump to bump-then-build.

- README.md
- api/server/routes_create.go
- api/server/routes_update.go
Removes image check when updating routes to make local testing possible without having to push to docker hub. Also mounts the docker socket in the quickstart to enable this. 
Thoughts?
Closes #514 
Closes #348
> Updates to enable local testing without Docker registry

- api/datastore/bolt/bolt.go
- api/datastore/internal/datastoreutil/validator.go
- api/datastore/mock.go
- api/datastore/mock_test.go
- api/datastore/postgres/postgres.go
- api/datastore/redis/redis.go
- api/models/datastore.go
- api/server/apps_test.go
- api/server/routes_test.go
- api/server/runner_async_test.go
- api/server/runner_test.go
This change cherry picks the common datastore validator from #523 to DRY up parameter validation from all the ```models.Datastore``` implementations.  No test behavior was changed, only mock initialization.
Notice that all implementations now have the same or better validation than before, and although there were inconsistencies between them, they all pass the same tests in both cases.  This means there are some untested edge cases possibly worth addressing.
> Datastore validator

- api/models/app.go
- api/models/route.go
- api/models/route_wrapper.go
- api/server/apps_delete.go
- api/server/routes_create.go
- api/server/routes_test.go
- api/server/routes_update.go
This change picks out more pieces of #523.
- Splits route validation and defaults into separate methods to leverage from route create and update.
- Improved and additional route test cases.
> server updates

- Makefile
Using golang:alpine instead of host go binary
Fixes: #559
> Make docker-test job pure Docker-based

- api/datastore/internal/datastoretest/test.go
- api/datastore/postgres/postgres_test.go
- api/datastore/redis/redis_test.go
Make tests consume DOCKER_HOST IP address as
bind host while constucting database URI.
This fix makes datastore tests pass against
remote Docker (with host IP different from 127.0.0.1)
Fixes: #586
> Make datastore tests pass with remote Docker containers

- api/mqs/ironmq.go
This change fixes a bug discovered in #581 which was breaking arm builds (#577).
I was able to run `GOARCH=arm GOARM=5 go build -o functions`.
> arm overflow s/ns fix

- Makefile
- circle.yml
Add ARM v5 (or greater) binary builder to ensure support maintained
Depends-On: #590
> Ensure can build ARM v5 or greater binaries

- api/runner/worker.go
So functions can know if they are running as hot function or not and which format has been defined.
> Add env vars for hotfunctions

- docs/README.md
- docs/lambda/README.md
- docs/lambda/about.md
- examples/hello/python/.gitignore
- examples/lambda/node/.gitignore
- examples/lambda/node/README.md
- examples/lambda/node/func.js
- examples/lambda/node/payload.json
- fn/common.go
- fn/deploy.go
- fn/funcfile.go
- fn/init.go
- fn/lambda.go
- fn/lambda/node/Dockerfile
- fn/lambda/node/bootstrap.js
- fn/lambda/node/build.sh
- fn/lambda/node/release.sh
- fn/langs/base.go
- fn/langs/dotnet.go
- fn/langs/go.go
- fn/langs/lambda_node.go
- fn/langs/node.go
- fn/langs/python.go
- fn/langs/ruby.go
- fn/langs/rust.go
- fn/routes.go
- fn/testfn.go
Using `--runtime lambda-node` will use the lambda wrapper for the function. 
```sh
fn init --runtime lambda-node <DOCKER_HUB_USERNAME>/lambda-node
```
The PR looks a lot bigger than it is, a lot of the files that were changed are minor. The main thing is the `fn/lambda` stuff that builds the `iron/functions-lambda:node` image. And I've added a `lambda-node` runtime that will use that image. Lastly, added "cmd" value to `func.yaml` since the lambda image requires use of the `ENTRYPOINT`.
> Added Lambda Node support as part of the regular functions workflow.

- api/datastore/mysql/mysql.go
- api/datastore/postgres/postgres.go
- api/models/new_task.go
- api/models/route.go
- api/runner/async_runner.go
- api/runner/task.go
- api/runner/task/task.go
- api/runner/worker.go
- api/server/runner.go
- docs/function-timeouts.md
- docs/hot-functions.md
- docs/swagger.yml
Adding `inactivity_timeout` to routes API. 
This change will allow users to define idle timeout for hot functions via API instead of having it hardcoded in `worker.go`.
Closes: #554
> Add idle_timeout to routes API

- api/datastore/postgres/postgres.go
Postgres datastore was not marshaling the App config during its insert, that behavior was resulting in issues when fetching the App and the datastore couldn't unmarshal the config.
The same issue was probably happening with the Route's headers in some situations.
This commit's idea is to always try to marshal configs and headers when inserting/updating Apps or Routes. But in Apps and Routes get methods, if the  config/headers unmarshal fails, it returns an empty config/headers.
> Solving postgres marshal/unmarshal issue

- fn/common/common.go
Current fn command doesn't read environment variable of `API_URL`.
So I set environment variables to viper.
> Set env variables to viper
