iron-io/functions

api/server/version.go
fnctl/install.sh
fnctl/main.go

Bumped version numbers - 0.1.0 - alpha release version

---

api/server/runner.go
api/server/runner_async_test.go
docs/apps.md
docs/operating/routes.md
docs/writing.md
examples/blog/README.md
examples/blog/function.go
examples/blog/test.sh
examples/checker/README.md
examples/redis/function.go
examples/redis/test.sh
examples/twitter/function.go
fnctl/README.md

all: drop CONFIG_ prefix for configuration

---

glide.lock
glide.yaml

package jwt-go is not being used by functions.

Remove unnecessary dep

---

api/models/mq.go
api/server/apps_test.go
api/server/routes_test.go
api/server/runner.go
api/server/runner_async_test.go
api/server/runner_test.go
api/server/server.go
api/server/server_test.go
main.go

Changes to let functions be more pluggable.

server.New signature changes and test fixes.

---

fn/common.go
fn/init.go
fn/langs/base.go
fn/langs/python.go

fn: add support for python

---

api/server/routes_delete.go
api/server/routes_get.go
api/server/routes_test.go
api/server/routes_update.go
docs/swagger.yml
fn/apps.go
fn/glide.lock
fn/glide.yaml
fn/publish.go
fn/routes.go

fn: improve UX 

---

fn/Makefile
fn/release.sh
release.sh

fn: automatic release

---

api/server/apps_create.go

api: improve app create error message

---

api/datastore/bolt/bolt.go

This PR fixes bolt UpdateRoute function when updating headers.

Fix bolt UpdateRoute header

---

api/runner/async_runner.go
api/runner/async_runner_test.go
api/runner/func_logger.go
api/runner/metric_logger.go
api/runner/runner.go
api/runner/runner_test.go
api/server/runner.go
api/server/runner_test.go
main.go

Changes on function/metric loggers

---

docs/swagger.yml

api: remove useless parameter in get task call

---

docs/writing.md

doc: add language libraries to the documentation

---

api/server/apps_delete.go

App delete handler was calling wrong method.

Apps delete listener call

---

docs/swagger.yml
fn/README.md
fn/main.go
fn/version.go

api,fn: entrypoint to return daemon version

---

docs/swagger.yml
fn/README.md
fn/funcfile.go
fn/publish.go
fn/routes.go

fn: add header configuration to route calls

---

fn/bump.go
fn/common.go

fn: improve how `build` handle missing version

---

examples/hello/ruby/README.md
examples/slackbot/guppy/README.md

fn: improve docs

---

docs/function-file.md
examples/testframework/local/README.md
examples/testframework/local/func.go
examples/testframework/local/func.yaml
examples/testframework/remote/README.md
examples/testframework/remote/func.go
examples/testframework/remote/func.yaml
fn/README.md
fn/funcfile.go
fn/glide.lock
fn/glide.yaml
fn/main.go
fn/routes.go
fn/run.go
fn/run_others.go
fn/run_windows.go
fn/testfn.go

fn: support for functions testing

---

api/server/version.go
docs/function-file.md

fn: improve funcfile doc

---

examples/hash/.gitignore
examples/hash/README.md
examples/hash/func.cs
examples/hash/project.json
fn/common.go
fn/init.go
fn/langs/base.go
fn/langs/dotnet.go
fnctl/langs/dotnet.go

Fixes https://github.com/iron-io/functions/issues/313

fn: support for dotnet

---

docs/databases/README.md

functions: fix documentation on Redis support for DB

---

api/runner/async_runner_test.go
api/runner/runner.go
api/runner/runner_test.go
api/server/apps_test.go
api/server/routes_test.go
api/server/runner_async_test.go
api/server/runner_test.go
api/server/server_test.go
main.go

functions: fix goroutine leak in runner

---

docs/operating/extending.md

Closes https://github.com/iron-io/functions/issues/365

Update listener docs

---

CONTRIBUTING.md

docs: explains the need of keep doc up-to-date

---

docs/README.md
docs/hot-containers.md

doc: hot containers

---

release.sh

fn: fix automated installer

---

fn/deploy.go
fn/funcfile.go

fn: funcfile.Headers are now simple maps

---

docs/operating/extending.md

Remove ifaces from docs

---

examples/slackbot/guppy/README.md
fn/langs/ruby.go

- introduces dependency installation for Ruby functions.

examples: update guppy example with latest fn functionalities

---

api/server/apps_test.go
api/server/routes_test.go
api/server/runner.go
api/server/server.go
docs/swagger.yml

Change update from PUT method to PATCH

---

README.md

doc: fix slack link

---

api/const.go
api/server/apps_delete.go
api/server/apps_get.go
api/server/apps_update.go
api/server/routes_create.go
api/server/routes_delete.go
api/server/routes_get.go
api/server/routes_list.go
api/server/routes_update.go
api/server/runner.go
api/server/runner_async_test.go
api/server/runner_test.go
api/server/server.go
api/server/server_test.go
api/server/special_handler.go
api/server/special_handler_test.go
init.go
main.go

This removes everything unnecessary to make it easy for people to extend functions.

Cleanup main

---

fn/apps.go
fn/images.go
fn/main.go
fn/routes.go

Change fn organization and keep aliases

---

fn/main.go

Added alias for "push", "run" and "call".

---

CHANGELOG.md
docs/operating/triggers.md

Documents Picasso triggers for OpenStack. Relates to #171

add link to openstack trigger example

---

README.md
docs/README.md
docs/operating/ui.md

@treeder thoughts?
also, should docker command be duplicated here

docs for functions ui

---

README.md

Doc fixes: change docker and curl commands so they will execute.

---

api/server/runner.go

Return 500 if trying to run path with non-existing image

---

fn/routes.go

Dry up fn tool

---

api/datastore/redis/redis.go
api/datastore/redis_test.go

Replaces static wait with a ping loop for redis docker container.

redis test ping loop

---

api/datastore/redis/redis.go

This change adapts the redis impl to pass the common datastore tests.

Redis datastore test fixes

---

README.md

I know the other URL is shorter, but this is much safer.

Use SSL install url for fn cli

---

README.md
docs/definitions.md
examples/hash/README.md
fn/apps.go
fn/deploy.go
fn/images.go
fn/lambda.go
fn/main.go
fn/routes.go
fn/run.go

- standardized required args validation
- routes create/update now prioritize args, over flags, over funcfile configuration
- removed deadcode
#557 shoud be fixed

fn improvements

---

docs/operating/extending.md

- removes special handlers info
- fixes broken links
- cosmetic edits

update extensions doc

---

fn/main.go

fix fn required arguments issue

---

docs/options.md

Add Docker remote API connection options

---

api/datastore/internal/datastoretest/test.go
api/datastore/postgres/postgres.go

This change picks a few small things from #523, and improves some additional error handling.
@martinpinto If it would be smoother to wait for #575 to merge first, or to open a PR against that branch, let me know.

Postgres datastore errors and cleanup

---

api/server/runner.go

Fix REQUEST_URL to reflect host and port of a client

---

api/datastore/internal/datastoretest/test.go
circle.yml

Switch to Go 1.8 installation inside CI
Partially Addresses: #588

Switch to Go 1.8 installation inside CI

---

api/datastore/datastore.go
api/datastore/internal/datastoretest/test.go
api/datastore/mysql/mysql.go
api/datastore/mysql/mysql_test.go
glide.lock
glide.yaml

Added MySQL driver to IronFunctions

Fix #418 Added MySQL as DB storage layer.

---

fn/common.go

fn push also adds latest tag

---

Gopkg.lock
Gopkg.toml
api/runner/task.go
api/server/server.go

fix go get

---

fn/common.go

Fixed docker push bug

---

examples/image_processing/inplace/.gitignore
examples/image_processing/inplace/Dockerfile
examples/image_processing/inplace/Gemfile
examples/image_processing/inplace/README.md
examples/image_processing/inplace/func.rb
examples/image_processing/s3upload/.gitignore
examples/image_processing/s3upload/Dockerfile
examples/image_processing/s3upload/Gemfile
examples/image_processing/s3upload/README.md
examples/image_processing/s3upload/func.rb

Add image processing examples
